/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JSeparator;

/**
 *
 * @author mateo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form inicioMDI
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new FondoPanel();
        jPanel1 = new javax.swing.JPanel();
        btnFactura = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnPedido = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        btnRecaudoFact = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        btnRecaudoPedido = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnFactura = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnPedido = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnRecaudoFact = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnRecaudoPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/5027815_cash_coin_money_paper_icon.png"))); // NOI18N
        btnFactura.setToolTipText("Factura");

        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/8665038_cart_flatbed_icon.png"))); // NOI18N
        btnPedido.setToolTipText("Pedido");

        btnRecaudoFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/7007504_payment_bill_invoice_receipt_business_icon.png"))); // NOI18N
        btnRecaudoFact.setToolTipText("Facturas Clientes");
        btnRecaudoFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecaudoFactActionPerformed(evt);
            }
        });

        btnRecaudoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/9025861_package_box_icon.png"))); // NOI18N
        btnRecaudoPedido.setToolTipText("Historial de Pedidos");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/9104334_sign out_logout_exit_out_icon.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator7)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator5)
            .addComponent(jSeparator4)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPedido)
                            .addComponent(btnRecaudoFact)
                            .addComponent(btnRecaudoPedido)
                            .addComponent(btnFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecaudoFact, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecaudoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 712, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        jMenu1.setBackground(new java.awt.Color(204, 204, 255));
        jMenu1.setText("Generar");
        jMenu1.setToolTipText("");

        mnFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnFactura.setBackground(new java.awt.Color(204, 204, 255));
        mnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/factura.png"))); // NOI18N
        mnFactura.setText("Factura");
        mnFactura.setBorder(null);
        jMenu1.add(mnFactura);
        jMenu1.add(jSeparator1);

        mnPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnPedido.setBackground(new java.awt.Color(204, 204, 255));
        mnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/carrito-de-compras.png"))); // NOI18N
        mnPedido.setText("Pedido");
        mnPedido.setBorder(null);
        mnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPedidoActionPerformed(evt);
            }
        });
        jMenu1.add(mnPedido);
        jMenu1.add(jSeparator3);

        mnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnSalir.setBackground(new java.awt.Color(204, 204, 255));
        mnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cerrar-sesion.png"))); // NOI18N
        mnSalir.setText("Salir");
        mnSalir.setBorder(null);
        jMenu1.add(mnSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(null);
        jMenu2.setText("Registros");

        mnRecaudoFact.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnRecaudoFact.setBackground(new java.awt.Color(204, 204, 255));
        mnRecaudoFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/libro-de-cheques.png"))); // NOI18N
        mnRecaudoFact.setText("Facturas Cliente");
        mnRecaudoFact.setBorder(null);
        mnRecaudoFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRecaudoFactActionPerformed(evt);
            }
        });
        jMenu2.add(mnRecaudoFact);
        jMenu2.add(jSeparator2);

        mnRecaudoPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnRecaudoPedido.setBackground(new java.awt.Color(204, 204, 255));
        mnRecaudoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/entrega-de-pedidos.png"))); // NOI18N
        mnRecaudoPedido.setText("Historial Pedidos");
        mnRecaudoPedido.setBorder(null);
        jMenu2.add(mnRecaudoPedido);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnRecaudoFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRecaudoFactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnRecaudoFactActionPerformed

    private void mnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnPedidoActionPerformed

    private void btnRecaudoFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecaudoFactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecaudoFactActionPerformed


    public JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param args the command line arguments
     */
    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JButton getBtnFactura() {
        return btnFactura;
    }

    public void setBtnFactura(JButton btnFactura) {
        this.btnFactura = btnFactura;
    }

    public JButton getBtnPedido() {
        return btnPedido;
    }

    public void setBtnPedido(JButton btnPedido) {
        this.btnPedido = btnPedido;
    }

    public JButton getBtnRecaudoFact() {
        return btnRecaudoFact;
    }

    public void setBtnRecaudoFact(JButton btnRecaudoFact) {
        this.btnRecaudoFact = btnRecaudoFact;
    }

    public JButton getBtnRecaudoPedido() {
        return btnRecaudoPedido;
    }

    public void setBtnRecaudoPedido(JButton btnRecaudoPedido) {
        this.btnRecaudoPedido = btnRecaudoPedido;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
        this.jDesktopPane1 = jDesktopPane1;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPopupMenu.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JPopupMenu.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JPopupMenu.Separator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JPopupMenu.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JPopupMenu.Separator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JPopupMenu.Separator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JSeparator getjSeparator4() {
        return jSeparator4;
    }

    public void setjSeparator4(JSeparator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }

    public JSeparator getjSeparator5() {
        return jSeparator5;
    }

    public void setjSeparator5(JSeparator jSeparator5) {
        this.jSeparator5 = jSeparator5;
    }

    public JSeparator getjSeparator6() {
        return jSeparator6;
    }

    public void setjSeparator6(JSeparator jSeparator6) {
        this.jSeparator6 = jSeparator6;
    }

    public JSeparator getjSeparator7() {
        return jSeparator7;
    }

    public void setjSeparator7(JSeparator jSeparator7) {
        this.jSeparator7 = jSeparator7;
    }

    public JMenuItem getMnFactura() {
        return mnFactura;
    }

    public void setMnFactura(JMenuItem mnFactura) {
        this.mnFactura = mnFactura;
    }

    public JMenuItem getMnPedido() {
        return mnPedido;
    }

    public void setMnPedido(JMenuItem mnPedido) {
        this.mnPedido = mnPedido;
    }

    public JMenuItem getMnRecaudoFact() {
        return mnRecaudoFact;
    }

    public void setMnRecaudoFact(JMenuItem mnRecaudoFact) {
        this.mnRecaudoFact = mnRecaudoFact;
    }

    public JMenuItem getMnRecaudoPedido() {
        return mnRecaudoPedido;
    }

    public void setMnRecaudoPedido(JMenuItem mnRecaudoPedido) {
        this.mnRecaudoPedido = mnRecaudoPedido;
    }

    public JMenuItem getMnSalir() {
        return mnSalir;
    }

    public void setMnSalir(JMenuItem mnSalir) {
        this.mnSalir = mnSalir;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnRecaudoFact;
    private javax.swing.JButton btnRecaudoPedido;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JMenuItem mnFactura;
    private javax.swing.JMenuItem mnPedido;
    private javax.swing.JMenuItem mnRecaudoFact;
    private javax.swing.JMenuItem mnRecaudoPedido;
    private javax.swing.JMenuItem mnSalir;
    // End of variables declaration//GEN-END:variables

}
